### ISSUE TITLE
MemoryError: memory allocation failed, allocating 80 bytes

### ISSUE THREAD

**Issue by reinux** [Dowster64/XBee3_SSD1306#1]
Hey,

I'm getting this exception:

> Traceback (most recent call last):
>  File "/flash/main.py", line 13, in <module>
>  File "/flash/xbee3_ssd1306.py", line 31, in <module>
> MemoryError: memory allocation failed, allocating 80 bytes

That's a pretty small amount of memory. Any idea why it might be having trouble allocating it?

Using an XBee 3 Zigbee.

Thanks!

**Comment by Dowster64** [comment]
HI @reinux  - Just a heads up - I would expect to see you flashing *.mpy files.   I've used 802.15.4 rather than Zigbee firmware.

**Comment by reinux** [comment]
Hey hey, it worked! These things are so cute.

It wasn't the mpy -- I just turned off compiling in PyCharm to see if that would make a difference. But using the 802.15.4 firmware instead of the Zigbee firmware did it.

Do you have any idea why the Zigbee firmware might not like it?

**Comment by Dowster64** [comment]
HI @reinux, It might not have been the Zigbee firmware per se.  One thing I came across (and it's in the documents) is that the space for files (the filesystem) gets used up - you have to format the filesystem to recover space.  Try doing that with the Zigbee firmware from pycharm (if you weren't doing that before) - you select 'format Xbee file system' from the digi menu.  AFAIK, there is no difference in micropython between Zigbee and 802.15.4.
What I'm suggesting is that when you switched firmware the filesystem would have been reformated - but that is just a guess.
I'm glad you've got it to work.  I like that they don't need another MCU to do simple stuff.

**Comment by reinux** [comment]
Huh, that's weird... I could have sworn there was enough space on the filesystem. I guess the number reported by XCTU isn't always accurate?

In any case, I got it working with the Zigbee firmware. Thanks!

And yeah, having a one-chip solution is great, especially now when stock isn't always predictable.
